// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ClusterInfoProvider is an autogenerated mock type for the ClusterInfoProvider type
type ClusterInfoProvider struct {
	mock.Mock
}

// IsLocal provides a mock function with given fields: key
func (_m *ClusterInfoProvider) IsLocal(key []byte) bool {
	ret := _m.Called(key)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]byte) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
