// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import interfaces "github.com/mhelmich/calvin/interfaces"
import mock "github.com/stretchr/testify/mock"
import raftpb "go.etcd.io/etcd/raft/raftpb"

// RaftMessageClient is an autogenerated mock type for the RaftMessageClient type
type RaftMessageClient struct {
	mock.Mock
}

// SendMessages provides a mock function with given fields: msgs
func (_m *RaftMessageClient) SendMessages(msgs []raftpb.Message) *interfaces.RaftMessageSendingResults {
	ret := _m.Called(msgs)

	var r0 *interfaces.RaftMessageSendingResults
	if rf, ok := ret.Get(0).(func([]raftpb.Message) *interfaces.RaftMessageSendingResults); ok {
		r0 = rf(msgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.RaftMessageSendingResults)
		}
	}

	return r0
}
