// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import pb "github.com/mhelmich/calvin/pb"

// RaftMessageServer is an autogenerated mock type for the RaftMessageServer type
type RaftMessageServer struct {
	mock.Mock
}

// Step provides a mock function with given fields: stream
func (_m *RaftMessageServer) Step(stream pb.RaftTransportService_StepServer) error {
	ret := _m.Called(stream)

	var r0 error
	if rf, ok := ret.Get(0).(func(pb.RaftTransportService_StepServer) error); ok {
		r0 = rf(stream)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
