// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import pb "github.com/mhelmich/calvin/pb"

// RemoteReadClient is an autogenerated mock type for the RemoteReadClient type
type RemoteReadClient struct {
	mock.Mock
}

// RemoteRead provides a mock function with given fields: ctx, in, opts
func (_m *RemoteReadClient) RemoteRead(ctx context.Context, in *pb.RemoteReadRequest, opts ...grpc.CallOption) (*pb.RemoteReadResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.RemoteReadResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.RemoteReadRequest, ...grpc.CallOption) *pb.RemoteReadResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.RemoteReadResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.RemoteReadRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
