// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import raftpb "go.etcd.io/etcd/raft/raftpb"

// SnapshotHandler is an autogenerated mock type for the SnapshotHandler type
type SnapshotHandler struct {
	mock.Mock
}

// Consume provides a mock function with given fields: snapshotData
func (_m *SnapshotHandler) Consume(snapshotData []byte) error {
	ret := _m.Called(snapshotData)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(snapshotData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Provide provides a mock function with given fields: lastSnapshot, entriesAppliedSinceLastSnapshot
func (_m *SnapshotHandler) Provide(lastSnapshot raftpb.Snapshot, entriesAppliedSinceLastSnapshot []raftpb.Entry) ([]byte, error) {
	ret := _m.Called(lastSnapshot, entriesAppliedSinceLastSnapshot)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(raftpb.Snapshot, []raftpb.Entry) []byte); ok {
		r0 = rf(lastSnapshot, entriesAppliedSinceLastSnapshot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(raftpb.Snapshot, []raftpb.Entry) error); ok {
		r1 = rf(lastSnapshot, entriesAppliedSinceLastSnapshot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
