// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/calvin.proto

package pb

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	raftpb "go.etcd.io/etcd/raft/raftpb"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Id128 struct {
	Upper                uint64   `protobuf:"varint,1,opt,name=Upper,proto3" json:"Upper,omitempty"`
	Lower                uint64   `protobuf:"varint,2,opt,name=Lower,proto3" json:"Lower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id128) Reset()         { *m = Id128{} }
func (m *Id128) String() string { return proto.CompactTextString(m) }
func (*Id128) ProtoMessage()    {}
func (*Id128) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc31d04251e05fb, []int{0}
}
func (m *Id128) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Id128) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Id128.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Id128) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id128.Merge(m, src)
}
func (m *Id128) XXX_Size() int {
	return m.Size()
}
func (m *Id128) XXX_DiscardUnknown() {
	xxx_messageInfo_Id128.DiscardUnknown(m)
}

var xxx_messageInfo_Id128 proto.InternalMessageInfo

type Transaction struct {
	Id *Id128 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// keys of the data objects that are being accessed
	WriteSet     [][]byte `protobuf:"bytes,2,rep,name=write_set,json=writeSet,proto3" json:"write_set,omitempty"`
	ReadSet      [][]byte `protobuf:"bytes,3,rep,name=read_set,json=readSet,proto3" json:"read_set,omitempty"`
	ReadWriteSet [][]byte `protobuf:"bytes,4,rep,name=read_write_set,json=readWriteSet,proto3" json:"read_write_set,omitempty"`
	// ids of the nodes that are being contacted
	ReaderNodes []int64 `protobuf:"varint,5,rep,packed,name=reader_nodes,json=readerNodes,proto3" json:"reader_nodes,omitempty"`
	WriterNodes []int64 `protobuf:"varint,6,rep,packed,name=writer_nodes,json=writerNodes,proto3" json:"writer_nodes,omitempty"`
	// the stored procedure that's being invoked
	StoredProcedure      string   `protobuf:"bytes,7,opt,name=stored_procedure,json=storedProcedure,proto3" json:"stored_procedure,omitempty"`
	StoredProcedureArgs  [][]byte `protobuf:"bytes,8,rep,name=stored_procedure_args,json=storedProcedureArgs,proto3" json:"stored_procedure_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc31d04251e05fb, []int{1}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return m.Size()
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

type TransactionBatch struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Term                 uint64         `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	Index                uint64         `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	NodeId               uint64         `protobuf:"varint,4,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionBatch) Reset()         { *m = TransactionBatch{} }
func (m *TransactionBatch) String() string { return proto.CompactTextString(m) }
func (*TransactionBatch) ProtoMessage()    {}
func (*TransactionBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc31d04251e05fb, []int{2}
}
func (m *TransactionBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransactionBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransactionBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransactionBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionBatch.Merge(m, src)
}
func (m *TransactionBatch) XXX_Size() int {
	return m.Size()
}
func (m *TransactionBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionBatch.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionBatch proto.InternalMessageInfo

type SequencerResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SequencerResponse) Reset()         { *m = SequencerResponse{} }
func (m *SequencerResponse) String() string { return proto.CompactTextString(m) }
func (*SequencerResponse) ProtoMessage()    {}
func (*SequencerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc31d04251e05fb, []int{3}
}
func (m *SequencerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SequencerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SequencerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SequencerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequencerResponse.Merge(m, src)
}
func (m *SequencerResponse) XXX_Size() int {
	return m.Size()
}
func (m *SequencerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SequencerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SequencerResponse proto.InternalMessageInfo

type LowIsolationReadRequest struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=Keys,proto3" json:"Keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LowIsolationReadRequest) Reset()         { *m = LowIsolationReadRequest{} }
func (m *LowIsolationReadRequest) String() string { return proto.CompactTextString(m) }
func (*LowIsolationReadRequest) ProtoMessage()    {}
func (*LowIsolationReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc31d04251e05fb, []int{4}
}
func (m *LowIsolationReadRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LowIsolationReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LowIsolationReadRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LowIsolationReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LowIsolationReadRequest.Merge(m, src)
}
func (m *LowIsolationReadRequest) XXX_Size() int {
	return m.Size()
}
func (m *LowIsolationReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LowIsolationReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LowIsolationReadRequest proto.InternalMessageInfo

type LowIsolationReadResponse struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=Keys,proto3" json:"Keys,omitempty"`
	Values               [][]byte `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
	Term                 uint64   `protobuf:"varint,3,opt,name=Term,proto3" json:"Term,omitempty"`
	Index                uint64   `protobuf:"varint,4,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LowIsolationReadResponse) Reset()         { *m = LowIsolationReadResponse{} }
func (m *LowIsolationReadResponse) String() string { return proto.CompactTextString(m) }
func (*LowIsolationReadResponse) ProtoMessage()    {}
func (*LowIsolationReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc31d04251e05fb, []int{5}
}
func (m *LowIsolationReadResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LowIsolationReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LowIsolationReadResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LowIsolationReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LowIsolationReadResponse.Merge(m, src)
}
func (m *LowIsolationReadResponse) XXX_Size() int {
	return m.Size()
}
func (m *LowIsolationReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LowIsolationReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LowIsolationReadResponse proto.InternalMessageInfo

type StepReq struct {
	RaftNodeId           int64           `protobuf:"varint,1,opt,name=RaftNodeId,proto3" json:"RaftNodeId,omitempty"`
	Message              *raftpb.Message `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StepReq) Reset()         { *m = StepReq{} }
func (m *StepReq) String() string { return proto.CompactTextString(m) }
func (*StepReq) ProtoMessage()    {}
func (*StepReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc31d04251e05fb, []int{6}
}
func (m *StepReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StepReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StepReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StepReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepReq.Merge(m, src)
}
func (m *StepReq) XXX_Size() int {
	return m.Size()
}
func (m *StepReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StepReq.DiscardUnknown(m)
}

var xxx_messageInfo_StepReq proto.InternalMessageInfo

type StepResp struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StepResp) Reset()         { *m = StepResp{} }
func (m *StepResp) String() string { return proto.CompactTextString(m) }
func (*StepResp) ProtoMessage()    {}
func (*StepResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc31d04251e05fb, []int{7}
}
func (m *StepResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StepResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StepResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StepResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepResp.Merge(m, src)
}
func (m *StepResp) XXX_Size() int {
	return m.Size()
}
func (m *StepResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StepResp.DiscardUnknown(m)
}

var xxx_messageInfo_StepResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Id128)(nil), "pb.Id128")
	proto.RegisterType((*Transaction)(nil), "pb.Transaction")
	proto.RegisterType((*TransactionBatch)(nil), "pb.TransactionBatch")
	proto.RegisterType((*SequencerResponse)(nil), "pb.SequencerResponse")
	proto.RegisterType((*LowIsolationReadRequest)(nil), "pb.LowIsolationReadRequest")
	proto.RegisterType((*LowIsolationReadResponse)(nil), "pb.LowIsolationReadResponse")
	proto.RegisterType((*StepReq)(nil), "pb.StepReq")
	proto.RegisterType((*StepResp)(nil), "pb.StepResp")
}

func init() { proto.RegisterFile("pb/calvin.proto", fileDescriptor_afc31d04251e05fb) }

var fileDescriptor_afc31d04251e05fb = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdf, 0x6e, 0x12, 0x4f,
	0x14, 0x66, 0x59, 0x5a, 0xe0, 0x40, 0x7e, 0xed, 0x6f, 0x6c, 0x75, 0x4b, 0xcd, 0x06, 0x37, 0x46,
	0xe9, 0x85, 0xa0, 0xdb, 0x9b, 0xde, 0x19, 0x9b, 0xf4, 0x82, 0x58, 0xff, 0x64, 0xa8, 0x7a, 0x63,
	0x42, 0x96, 0x9d, 0x53, 0xba, 0x09, 0xee, 0x4c, 0x67, 0x86, 0x56, 0x1f, 0xc1, 0x37, 0xf0, 0x1d,
	0x7c, 0x91, 0x5e, 0xf6, 0x11, 0x6c, 0x7d, 0x11, 0x33, 0x33, 0x4b, 0x8b, 0x14, 0x6f, 0xd8, 0xf9,
	0xbe, 0xf3, 0xcd, 0xd9, 0xf3, 0x7d, 0x07, 0x80, 0x35, 0x31, 0xea, 0xa5, 0xc9, 0xe4, 0x2c, 0xcb,
	0xbb, 0x42, 0x72, 0xcd, 0x49, 0x59, 0x8c, 0x5a, 0x1b, 0x63, 0x3e, 0xe6, 0x16, 0xf6, 0xcc, 0xc9,
	0x55, 0x5a, 0x4f, 0xc6, 0xbc, 0x8b, 0x3a, 0x65, 0xdd, 0x8c, 0xf7, 0xcc, 0xb3, 0x27, 0x93, 0x63,
	0x6d, 0x3f, 0xc4, 0xc8, 0x3e, 0x9c, 0x2e, 0xda, 0x85, 0x95, 0x3e, 0x7b, 0x11, 0xef, 0x91, 0x0d,
	0x58, 0xf9, 0x20, 0x04, 0xca, 0xc0, 0x6b, 0x7b, 0x9d, 0x0a, 0x75, 0xc0, 0xb0, 0x87, 0xfc, 0x1c,
	0x65, 0x50, 0x76, 0xac, 0x05, 0xd1, 0xcf, 0x32, 0x34, 0x8e, 0x64, 0x92, 0xab, 0x24, 0xd5, 0x19,
	0xcf, 0xc9, 0x16, 0x94, 0x33, 0x66, 0x2f, 0x36, 0xe2, 0x7a, 0x57, 0x8c, 0xba, 0xb6, 0x25, 0x2d,
	0x67, 0x8c, 0x6c, 0x43, 0xfd, 0x5c, 0x66, 0x1a, 0x87, 0x0a, 0x75, 0x50, 0x6e, 0xfb, 0x9d, 0x26,
	0xad, 0x59, 0x62, 0x80, 0x9a, 0x6c, 0x41, 0x4d, 0x62, 0xc2, 0x6c, 0xcd, 0xb7, 0xb5, 0xaa, 0xc1,
	0xa6, 0xf4, 0x18, 0xfe, 0xb3, 0xa5, 0xdb, 0xcb, 0x15, 0x2b, 0x68, 0x1a, 0xf6, 0xd3, 0xac, 0xc1,
	0x23, 0xb0, 0x18, 0xe5, 0x30, 0xe7, 0x0c, 0x55, 0xb0, 0xd2, 0xf6, 0x3b, 0x3e, 0x6d, 0x38, 0xee,
	0xad, 0xa1, 0x8c, 0xc4, 0xf6, 0x98, 0x49, 0x56, 0x9d, 0xc4, 0x71, 0x4e, 0xb2, 0x03, 0xeb, 0x4a,
	0x73, 0x89, 0x6c, 0x28, 0x24, 0x4f, 0x91, 0x4d, 0x25, 0x06, 0xd5, 0xb6, 0xd7, 0xa9, 0xd3, 0x35,
	0xc7, 0xbf, 0x9f, 0xd1, 0x24, 0x86, 0xcd, 0x45, 0xe9, 0x30, 0x91, 0x63, 0x15, 0xd4, 0xec, 0x74,
	0xf7, 0x16, 0xf4, 0xaf, 0xe4, 0x58, 0x45, 0xdf, 0x3d, 0x58, 0x9f, 0x4b, 0x6b, 0x3f, 0xd1, 0xe9,
	0x09, 0xd9, 0x85, 0xa6, 0xbe, 0xe5, 0x54, 0xe0, 0xb5, 0xfd, 0x4e, 0x23, 0x5e, 0x33, 0xe1, 0xcd,
	0x69, 0xe9, 0x5f, 0x22, 0x42, 0xa0, 0x72, 0x84, 0xf2, 0x4b, 0xb1, 0x0c, 0x7b, 0x36, 0x1b, 0xea,
	0xe7, 0x0c, 0xbf, 0x06, 0xbe, 0xdb, 0x90, 0x05, 0xe4, 0x3e, 0xac, 0x1a, 0x6f, 0x7d, 0x16, 0x54,
	0x2c, 0x5d, 0xa0, 0x68, 0x07, 0xfe, 0x1f, 0xe0, 0xe9, 0x14, 0xf3, 0x14, 0x25, 0x45, 0x25, 0x78,
	0xae, 0xd0, 0xb4, 0x38, 0x90, 0x92, 0xbb, 0xd5, 0xd7, 0xa9, 0x03, 0xd1, 0x33, 0x78, 0x70, 0xc8,
	0xcf, 0xfb, 0x8a, 0x4f, 0x12, 0x3b, 0x0a, 0x26, 0x8c, 0x9a, 0xab, 0x4a, 0x9b, 0x39, 0x5e, 0xe3,
	0x37, 0x37, 0x74, 0x93, 0xda, 0x73, 0x24, 0x20, 0xb8, 0x2b, 0x2f, 0x5e, 0xb0, 0x44, 0x6f, 0x26,
	0xfc, 0x98, 0x4c, 0xa6, 0xa8, 0x8a, 0x6f, 0x45, 0x81, 0x6e, 0x3c, 0xfa, 0xcb, 0x3c, 0x56, 0xe6,
	0x3c, 0x46, 0x47, 0x50, 0x1d, 0x68, 0x14, 0x14, 0x4f, 0x49, 0x08, 0x40, 0x93, 0x63, 0x5d, 0x58,
	0x36, 0x36, 0x7c, 0x3a, 0xc7, 0x90, 0x1d, 0xa8, 0xbe, 0x41, 0xa5, 0x92, 0x31, 0xda, 0xec, 0x4c,
	0xd0, 0xee, 0xa7, 0xd0, 0x2d, 0x68, 0x3a, 0xab, 0x47, 0x6d, 0xa8, 0xb9, 0xae, 0x4a, 0x2c, 0x0f,
	0x26, 0x3e, 0x80, 0xfa, 0x4d, 0x86, 0x64, 0x0f, 0x6a, 0xaa, 0x00, 0x64, 0x71, 0x7b, 0xad, 0x4d,
	0x43, 0xdc, 0xc9, 0x3b, 0x2a, 0x75, 0xbc, 0xe7, 0x5e, 0xfc, 0x19, 0xea, 0x83, 0xf4, 0x04, 0xd9,
	0x74, 0x82, 0x92, 0xbc, 0x83, 0xf5, 0xc9, 0x42, 0x7a, 0x64, 0xdb, 0xdc, 0xfe, 0xc7, 0x0a, 0x5a,
	0x0f, 0x97, 0x17, 0x67, 0x6f, 0x88, 0x5f, 0xc2, 0x86, 0xf1, 0x6f, 0xa7, 0x11, 0x5c, 0xea, 0x01,
	0xca, 0xb3, 0x2c, 0x45, 0xf2, 0x14, 0x2a, 0xc6, 0x1e, 0x69, 0xd8, 0xd1, 0x5c, 0x7c, 0xad, 0xe6,
	0x2d, 0x50, 0xc2, 0x8d, 0xb7, 0x1f, 0x5c, 0x5c, 0x85, 0xa5, 0xcb, 0xab, 0xb0, 0x74, 0x71, 0x1d,
	0x7a, 0x97, 0xd7, 0xa1, 0xf7, 0xeb, 0x3a, 0xf4, 0x7e, 0xfc, 0x0e, 0x4b, 0xa3, 0x55, 0xfb, 0xcf,
	0xb1, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0x28, 0x39, 0x5f, 0xbe, 0x8e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SequencerClient is the client API for Sequencer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SequencerClient interface {
	Sequence(ctx context.Context, opts ...grpc.CallOption) (Sequencer_SequenceClient, error)
}

type sequencerClient struct {
	cc *grpc.ClientConn
}

func NewSequencerClient(cc *grpc.ClientConn) SequencerClient {
	return &sequencerClient{cc}
}

func (c *sequencerClient) Sequence(ctx context.Context, opts ...grpc.CallOption) (Sequencer_SequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sequencer_serviceDesc.Streams[0], "/pb.Sequencer/sequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &sequencerSequenceClient{stream}
	return x, nil
}

type Sequencer_SequenceClient interface {
	Send(*Transaction) error
	Recv() (*SequencerResponse, error)
	grpc.ClientStream
}

type sequencerSequenceClient struct {
	grpc.ClientStream
}

func (x *sequencerSequenceClient) Send(m *Transaction) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sequencerSequenceClient) Recv() (*SequencerResponse, error) {
	m := new(SequencerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SequencerServer is the server API for Sequencer service.
type SequencerServer interface {
	Sequence(Sequencer_SequenceServer) error
}

func RegisterSequencerServer(s *grpc.Server, srv SequencerServer) {
	s.RegisterService(&_Sequencer_serviceDesc, srv)
}

func _Sequencer_Sequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SequencerServer).Sequence(&sequencerSequenceServer{stream})
}

type Sequencer_SequenceServer interface {
	Send(*SequencerResponse) error
	Recv() (*Transaction, error)
	grpc.ServerStream
}

type sequencerSequenceServer struct {
	grpc.ServerStream
}

func (x *sequencerSequenceServer) Send(m *SequencerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sequencerSequenceServer) Recv() (*Transaction, error) {
	m := new(Transaction)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Sequencer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Sequencer",
	HandlerType: (*SequencerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "sequence",
			Handler:       _Sequencer_Sequence_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/calvin.proto",
}

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulerClient interface {
	LowIsolationRead(ctx context.Context, in *LowIsolationReadRequest, opts ...grpc.CallOption) (*LowIsolationReadResponse, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) LowIsolationRead(ctx context.Context, in *LowIsolationReadRequest, opts ...grpc.CallOption) (*LowIsolationReadResponse, error) {
	out := new(LowIsolationReadResponse)
	err := c.cc.Invoke(ctx, "/pb.Scheduler/lowIsolationRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
type SchedulerServer interface {
	LowIsolationRead(context.Context, *LowIsolationReadRequest) (*LowIsolationReadResponse, error)
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_LowIsolationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LowIsolationReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).LowIsolationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Scheduler/LowIsolationRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).LowIsolationRead(ctx, req.(*LowIsolationReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "lowIsolationRead",
			Handler:    _Scheduler_LowIsolationRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/calvin.proto",
}

// RaftTransportServiceClient is the client API for RaftTransportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftTransportServiceClient interface {
	Step(ctx context.Context, opts ...grpc.CallOption) (RaftTransportService_StepClient, error)
}

type raftTransportServiceClient struct {
	cc *grpc.ClientConn
}

func NewRaftTransportServiceClient(cc *grpc.ClientConn) RaftTransportServiceClient {
	return &raftTransportServiceClient{cc}
}

func (c *raftTransportServiceClient) Step(ctx context.Context, opts ...grpc.CallOption) (RaftTransportService_StepClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RaftTransportService_serviceDesc.Streams[0], "/pb.RaftTransportService/Step", opts...)
	if err != nil {
		return nil, err
	}
	x := &raftTransportServiceStepClient{stream}
	return x, nil
}

type RaftTransportService_StepClient interface {
	Send(*StepReq) error
	Recv() (*StepResp, error)
	grpc.ClientStream
}

type raftTransportServiceStepClient struct {
	grpc.ClientStream
}

func (x *raftTransportServiceStepClient) Send(m *StepReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *raftTransportServiceStepClient) Recv() (*StepResp, error) {
	m := new(StepResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RaftTransportServiceServer is the server API for RaftTransportService service.
type RaftTransportServiceServer interface {
	Step(RaftTransportService_StepServer) error
}

func RegisterRaftTransportServiceServer(s *grpc.Server, srv RaftTransportServiceServer) {
	s.RegisterService(&_RaftTransportService_serviceDesc, srv)
}

func _RaftTransportService_Step_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftTransportServiceServer).Step(&raftTransportServiceStepServer{stream})
}

type RaftTransportService_StepServer interface {
	Send(*StepResp) error
	Recv() (*StepReq, error)
	grpc.ServerStream
}

type raftTransportServiceStepServer struct {
	grpc.ServerStream
}

func (x *raftTransportServiceStepServer) Send(m *StepResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *raftTransportServiceStepServer) Recv() (*StepReq, error) {
	m := new(StepReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RaftTransportService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RaftTransportService",
	HandlerType: (*RaftTransportServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Step",
			Handler:       _RaftTransportService_Step_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/calvin.proto",
}

func (m *Id128) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Id128) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Upper != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Upper))
	}
	if m.Lower != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Lower))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Transaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Transaction) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Id.Size()))
		n1, err := m.Id.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.WriteSet) > 0 {
		for _, b := range m.WriteSet {
			dAtA[i] = 0x12
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.ReadSet) > 0 {
		for _, b := range m.ReadSet {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.ReadWriteSet) > 0 {
		for _, b := range m.ReadWriteSet {
			dAtA[i] = 0x22
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.ReaderNodes) > 0 {
		dAtA3 := make([]byte, len(m.ReaderNodes)*10)
		var j2 int
		for _, num1 := range m.ReaderNodes {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		dAtA[i] = 0x2a
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(j2))
		i += copy(dAtA[i:], dAtA3[:j2])
	}
	if len(m.WriterNodes) > 0 {
		dAtA5 := make([]byte, len(m.WriterNodes)*10)
		var j4 int
		for _, num1 := range m.WriterNodes {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA5[j4] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j4++
			}
			dAtA5[j4] = uint8(num)
			j4++
		}
		dAtA[i] = 0x32
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(j4))
		i += copy(dAtA[i:], dAtA5[:j4])
	}
	if len(m.StoredProcedure) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(len(m.StoredProcedure)))
		i += copy(dAtA[i:], m.StoredProcedure)
	}
	if len(m.StoredProcedureArgs) > 0 {
		for _, b := range m.StoredProcedureArgs {
			dAtA[i] = 0x42
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TransactionBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransactionBatch) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for _, msg := range m.Transactions {
			dAtA[i] = 0xa
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Term != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Term))
	}
	if m.Index != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Index))
	}
	if m.NodeId != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.NodeId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *SequencerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SequencerResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(len(m.Error)))
		i += copy(dAtA[i:], m.Error)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *LowIsolationReadRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LowIsolationReadRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Keys) > 0 {
		for _, b := range m.Keys {
			dAtA[i] = 0xa
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *LowIsolationReadResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LowIsolationReadResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Keys) > 0 {
		for _, b := range m.Keys {
			dAtA[i] = 0xa
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.Values) > 0 {
		for _, b := range m.Values {
			dAtA[i] = 0x12
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if m.Term != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Term))
	}
	if m.Index != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Index))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *StepReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StepReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RaftNodeId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.RaftNodeId))
	}
	if m.Message != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Message.Size()))
		n6, err := m.Message.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *StepResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StepResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(len(m.Error)))
		i += copy(dAtA[i:], m.Error)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintCalvin(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Id128) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Upper != 0 {
		n += 1 + sovCalvin(uint64(m.Upper))
	}
	if m.Lower != 0 {
		n += 1 + sovCalvin(uint64(m.Lower))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Transaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != nil {
		l = m.Id.Size()
		n += 1 + l + sovCalvin(uint64(l))
	}
	if len(m.WriteSet) > 0 {
		for _, b := range m.WriteSet {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if len(m.ReadSet) > 0 {
		for _, b := range m.ReadSet {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if len(m.ReadWriteSet) > 0 {
		for _, b := range m.ReadWriteSet {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if len(m.ReaderNodes) > 0 {
		l = 0
		for _, e := range m.ReaderNodes {
			l += sovCalvin(uint64(e))
		}
		n += 1 + sovCalvin(uint64(l)) + l
	}
	if len(m.WriterNodes) > 0 {
		l = 0
		for _, e := range m.WriterNodes {
			l += sovCalvin(uint64(e))
		}
		n += 1 + sovCalvin(uint64(l)) + l
	}
	l = len(m.StoredProcedure)
	if l > 0 {
		n += 1 + l + sovCalvin(uint64(l))
	}
	if len(m.StoredProcedureArgs) > 0 {
		for _, b := range m.StoredProcedureArgs {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TransactionBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for _, e := range m.Transactions {
			l = e.Size()
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if m.Term != 0 {
		n += 1 + sovCalvin(uint64(m.Term))
	}
	if m.Index != 0 {
		n += 1 + sovCalvin(uint64(m.Index))
	}
	if m.NodeId != 0 {
		n += 1 + sovCalvin(uint64(m.NodeId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SequencerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovCalvin(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *LowIsolationReadRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Keys) > 0 {
		for _, b := range m.Keys {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *LowIsolationReadResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Keys) > 0 {
		for _, b := range m.Keys {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if len(m.Values) > 0 {
		for _, b := range m.Values {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if m.Term != 0 {
		n += 1 + sovCalvin(uint64(m.Term))
	}
	if m.Index != 0 {
		n += 1 + sovCalvin(uint64(m.Index))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StepReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RaftNodeId != 0 {
		n += 1 + sovCalvin(uint64(m.RaftNodeId))
	}
	if m.Message != nil {
		l = m.Message.Size()
		n += 1 + l + sovCalvin(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StepResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovCalvin(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCalvin(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCalvin(x uint64) (n int) {
	return sovCalvin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Id128) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Id128: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Id128: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Upper", wireType)
			}
			m.Upper = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Upper |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lower", wireType)
			}
			m.Lower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lower |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Transaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Transaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Transaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Id == nil {
				m.Id = &Id128{}
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriteSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WriteSet = append(m.WriteSet, make([]byte, postIndex-iNdEx))
			copy(m.WriteSet[len(m.WriteSet)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReadSet = append(m.ReadSet, make([]byte, postIndex-iNdEx))
			copy(m.ReadSet[len(m.ReadSet)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadWriteSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReadWriteSet = append(m.ReadWriteSet, make([]byte, postIndex-iNdEx))
			copy(m.ReadWriteSet[len(m.ReadWriteSet)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReaderNodes = append(m.ReaderNodes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthCalvin
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthCalvin
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ReaderNodes) == 0 {
					m.ReaderNodes = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCalvin
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReaderNodes = append(m.ReaderNodes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReaderNodes", wireType)
			}
		case 6:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.WriterNodes = append(m.WriterNodes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthCalvin
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthCalvin
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.WriterNodes) == 0 {
					m.WriterNodes = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCalvin
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.WriterNodes = append(m.WriterNodes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field WriterNodes", wireType)
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredProcedure", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoredProcedure = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredProcedureArgs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoredProcedureArgs = append(m.StoredProcedureArgs, make([]byte, postIndex-iNdEx))
			copy(m.StoredProcedureArgs[len(m.StoredProcedureArgs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransactionBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransactionBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransactionBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, &Transaction{})
			if err := m.Transactions[len(m.Transactions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Term", wireType)
			}
			m.Term = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Term |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			m.NodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SequencerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SequencerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SequencerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LowIsolationReadRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LowIsolationReadRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LowIsolationReadRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keys", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keys = append(m.Keys, make([]byte, postIndex-iNdEx))
			copy(m.Keys[len(m.Keys)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LowIsolationReadResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LowIsolationReadResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LowIsolationReadResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keys", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keys = append(m.Keys, make([]byte, postIndex-iNdEx))
			copy(m.Keys[len(m.Keys)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Values", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Values = append(m.Values, make([]byte, postIndex-iNdEx))
			copy(m.Values[len(m.Values)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Term", wireType)
			}
			m.Term = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Term |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StepReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StepReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StepReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftNodeId", wireType)
			}
			m.RaftNodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftNodeId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Message == nil {
				m.Message = &raftpb.Message{}
			}
			if err := m.Message.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StepResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StepResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StepResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCalvin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCalvin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCalvin
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthCalvin
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCalvin(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthCalvin
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCalvin = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCalvin   = fmt.Errorf("proto: integer overflow")
)
