// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/calvin.proto

/*
	Package pb is a generated protocol buffer package.

	It is generated from these files:
		pb/calvin.proto

	It has these top-level messages:
		Transaction
		TransactionBatch
		StepReq
		StepResp
		Id128
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import raftpb "go.etcd.io/etcd/raft/raftpb"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	// keys of the data objects that are being accessed
	WriteSet     [][]byte `protobuf:"bytes,10,rep,name=write_set,json=writeSet" json:"write_set,omitempty"`
	ReadSet      [][]byte `protobuf:"bytes,11,rep,name=read_set,json=readSet" json:"read_set,omitempty"`
	ReadWriteSet [][]byte `protobuf:"bytes,12,rep,name=read_write_set,json=readWriteSet" json:"read_write_set,omitempty"`
	// ids of the nodes that are being contacted
	ReaderNodes []int64 `protobuf:"varint,20,rep,packed,name=reader_nodes,json=readerNodes" json:"reader_nodes,omitempty"`
	WriterNodes []int64 `protobuf:"varint,21,rep,packed,name=writer_nodes,json=writerNodes" json:"writer_nodes,omitempty"`
	// the stored procedure that's being invoked
	StoredProcedure     string `protobuf:"bytes,30,opt,name=stored_procedure,json=storedProcedure,proto3" json:"stored_procedure,omitempty"`
	StoredProcedureArgs []byte `protobuf:"bytes,31,opt,name=stored_procedure_args,json=storedProcedureArgs,proto3" json:"stored_procedure_args,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptorCalvin, []int{0} }

type TransactionBatch struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *TransactionBatch) Reset()                    { *m = TransactionBatch{} }
func (m *TransactionBatch) String() string            { return proto.CompactTextString(m) }
func (*TransactionBatch) ProtoMessage()               {}
func (*TransactionBatch) Descriptor() ([]byte, []int) { return fileDescriptorCalvin, []int{1} }

type StepReq struct {
	RaftNodeId int64           `protobuf:"varint,1,opt,name=RaftNodeId,proto3" json:"RaftNodeId,omitempty"`
	Message    *raftpb.Message `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
}

func (m *StepReq) Reset()                    { *m = StepReq{} }
func (m *StepReq) String() string            { return proto.CompactTextString(m) }
func (*StepReq) ProtoMessage()               {}
func (*StepReq) Descriptor() ([]byte, []int) { return fileDescriptorCalvin, []int{2} }

type StepResp struct {
	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (m *StepResp) Reset()                    { *m = StepResp{} }
func (m *StepResp) String() string            { return proto.CompactTextString(m) }
func (*StepResp) ProtoMessage()               {}
func (*StepResp) Descriptor() ([]byte, []int) { return fileDescriptorCalvin, []int{3} }

type Id128 struct {
	Upper uint64 `protobuf:"varint,1,opt,name=Upper,proto3" json:"Upper,omitempty"`
	Lower uint64 `protobuf:"varint,2,opt,name=Lower,proto3" json:"Lower,omitempty"`
}

func (m *Id128) Reset()                    { *m = Id128{} }
func (m *Id128) String() string            { return proto.CompactTextString(m) }
func (*Id128) ProtoMessage()               {}
func (*Id128) Descriptor() ([]byte, []int) { return fileDescriptorCalvin, []int{4} }

func init() {
	proto.RegisterType((*Transaction)(nil), "pb.Transaction")
	proto.RegisterType((*TransactionBatch)(nil), "pb.TransactionBatch")
	proto.RegisterType((*StepReq)(nil), "pb.StepReq")
	proto.RegisterType((*StepResp)(nil), "pb.StepResp")
	proto.RegisterType((*Id128)(nil), "pb.Id128")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RaftTransportService service

type RaftTransportServiceClient interface {
	Step(ctx context.Context, opts ...grpc.CallOption) (RaftTransportService_StepClient, error)
}

type raftTransportServiceClient struct {
	cc *grpc.ClientConn
}

func NewRaftTransportServiceClient(cc *grpc.ClientConn) RaftTransportServiceClient {
	return &raftTransportServiceClient{cc}
}

func (c *raftTransportServiceClient) Step(ctx context.Context, opts ...grpc.CallOption) (RaftTransportService_StepClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RaftTransportService_serviceDesc.Streams[0], c.cc, "/pb.RaftTransportService/Step", opts...)
	if err != nil {
		return nil, err
	}
	x := &raftTransportServiceStepClient{stream}
	return x, nil
}

type RaftTransportService_StepClient interface {
	Send(*StepReq) error
	Recv() (*StepResp, error)
	grpc.ClientStream
}

type raftTransportServiceStepClient struct {
	grpc.ClientStream
}

func (x *raftTransportServiceStepClient) Send(m *StepReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *raftTransportServiceStepClient) Recv() (*StepResp, error) {
	m := new(StepResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RaftTransportService service

type RaftTransportServiceServer interface {
	Step(RaftTransportService_StepServer) error
}

func RegisterRaftTransportServiceServer(s *grpc.Server, srv RaftTransportServiceServer) {
	s.RegisterService(&_RaftTransportService_serviceDesc, srv)
}

func _RaftTransportService_Step_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftTransportServiceServer).Step(&raftTransportServiceStepServer{stream})
}

type RaftTransportService_StepServer interface {
	Send(*StepResp) error
	Recv() (*StepReq, error)
	grpc.ServerStream
}

type raftTransportServiceStepServer struct {
	grpc.ServerStream
}

func (x *raftTransportServiceStepServer) Send(m *StepResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *raftTransportServiceStepServer) Recv() (*StepReq, error) {
	m := new(StepReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RaftTransportService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RaftTransportService",
	HandlerType: (*RaftTransportServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Step",
			Handler:       _RaftTransportService_Step_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/calvin.proto",
}

func (m *Transaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Transaction) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.WriteSet) > 0 {
		for _, b := range m.WriteSet {
			dAtA[i] = 0x52
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.ReadSet) > 0 {
		for _, b := range m.ReadSet {
			dAtA[i] = 0x5a
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.ReadWriteSet) > 0 {
		for _, b := range m.ReadWriteSet {
			dAtA[i] = 0x62
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.ReaderNodes) > 0 {
		dAtA2 := make([]byte, len(m.ReaderNodes)*10)
		var j1 int
		for _, num1 := range m.ReaderNodes {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.WriterNodes) > 0 {
		dAtA4 := make([]byte, len(m.WriterNodes)*10)
		var j3 int
		for _, num1 := range m.WriterNodes {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0xaa
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	if len(m.StoredProcedure) > 0 {
		dAtA[i] = 0xf2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(len(m.StoredProcedure)))
		i += copy(dAtA[i:], m.StoredProcedure)
	}
	if len(m.StoredProcedureArgs) > 0 {
		dAtA[i] = 0xfa
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(len(m.StoredProcedureArgs)))
		i += copy(dAtA[i:], m.StoredProcedureArgs)
	}
	return i, nil
}

func (m *TransactionBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransactionBatch) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for _, msg := range m.Transactions {
			dAtA[i] = 0xa
			i++
			i = encodeVarintCalvin(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *StepReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StepReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RaftNodeId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.RaftNodeId))
	}
	if m.Message != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Message.Size()))
		n5, err := m.Message.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}

func (m *StepResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StepResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(len(m.Error)))
		i += copy(dAtA[i:], m.Error)
	}
	return i, nil
}

func (m *Id128) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Id128) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Upper != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Upper))
	}
	if m.Lower != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintCalvin(dAtA, i, uint64(m.Lower))
	}
	return i, nil
}

func encodeVarintCalvin(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Transaction) Size() (n int) {
	var l int
	_ = l
	if len(m.WriteSet) > 0 {
		for _, b := range m.WriteSet {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if len(m.ReadSet) > 0 {
		for _, b := range m.ReadSet {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if len(m.ReadWriteSet) > 0 {
		for _, b := range m.ReadWriteSet {
			l = len(b)
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	if len(m.ReaderNodes) > 0 {
		l = 0
		for _, e := range m.ReaderNodes {
			l += sovCalvin(uint64(e))
		}
		n += 2 + sovCalvin(uint64(l)) + l
	}
	if len(m.WriterNodes) > 0 {
		l = 0
		for _, e := range m.WriterNodes {
			l += sovCalvin(uint64(e))
		}
		n += 2 + sovCalvin(uint64(l)) + l
	}
	l = len(m.StoredProcedure)
	if l > 0 {
		n += 2 + l + sovCalvin(uint64(l))
	}
	l = len(m.StoredProcedureArgs)
	if l > 0 {
		n += 2 + l + sovCalvin(uint64(l))
	}
	return n
}

func (m *TransactionBatch) Size() (n int) {
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for _, e := range m.Transactions {
			l = e.Size()
			n += 1 + l + sovCalvin(uint64(l))
		}
	}
	return n
}

func (m *StepReq) Size() (n int) {
	var l int
	_ = l
	if m.RaftNodeId != 0 {
		n += 1 + sovCalvin(uint64(m.RaftNodeId))
	}
	if m.Message != nil {
		l = m.Message.Size()
		n += 1 + l + sovCalvin(uint64(l))
	}
	return n
}

func (m *StepResp) Size() (n int) {
	var l int
	_ = l
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovCalvin(uint64(l))
	}
	return n
}

func (m *Id128) Size() (n int) {
	var l int
	_ = l
	if m.Upper != 0 {
		n += 1 + sovCalvin(uint64(m.Upper))
	}
	if m.Lower != 0 {
		n += 1 + sovCalvin(uint64(m.Lower))
	}
	return n
}

func sovCalvin(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCalvin(x uint64) (n int) {
	return sovCalvin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Transaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Transaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Transaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriteSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WriteSet = append(m.WriteSet, make([]byte, postIndex-iNdEx))
			copy(m.WriteSet[len(m.WriteSet)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReadSet = append(m.ReadSet, make([]byte, postIndex-iNdEx))
			copy(m.ReadSet[len(m.ReadSet)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadWriteSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReadWriteSet = append(m.ReadWriteSet, make([]byte, postIndex-iNdEx))
			copy(m.ReadWriteSet[len(m.ReadWriteSet)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 20:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReaderNodes = append(m.ReaderNodes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthCalvin
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCalvin
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReaderNodes = append(m.ReaderNodes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReaderNodes", wireType)
			}
		case 21:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.WriterNodes = append(m.WriterNodes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthCalvin
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCalvin
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.WriterNodes = append(m.WriterNodes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field WriterNodes", wireType)
			}
		case 30:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredProcedure", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoredProcedure = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 31:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredProcedureArgs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoredProcedureArgs = append(m.StoredProcedureArgs[:0], dAtA[iNdEx:postIndex]...)
			if m.StoredProcedureArgs == nil {
				m.StoredProcedureArgs = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransactionBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransactionBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransactionBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, &Transaction{})
			if err := m.Transactions[len(m.Transactions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StepReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StepReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StepReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftNodeId", wireType)
			}
			m.RaftNodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftNodeId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Message == nil {
				m.Message = &raftpb.Message{}
			}
			if err := m.Message.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StepResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StepResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StepResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCalvin
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Id128) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Id128: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Id128: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Upper", wireType)
			}
			m.Upper = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Upper |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lower", wireType)
			}
			m.Lower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lower |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCalvin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCalvin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCalvin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCalvin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCalvin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCalvin
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCalvin
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCalvin(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCalvin = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCalvin   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("pb/calvin.proto", fileDescriptorCalvin) }

var fileDescriptorCalvin = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xd1, 0x6e, 0xd3, 0x30,
	0x18, 0x85, 0xeb, 0xa6, 0xa3, 0xed, 0x9f, 0x88, 0x4e, 0x26, 0x93, 0x42, 0x91, 0x42, 0x88, 0x10,
	0x64, 0x37, 0x29, 0xb4, 0x37, 0xdc, 0x21, 0x26, 0x21, 0x34, 0x09, 0x10, 0x72, 0x87, 0xb8, 0xac,
	0x9c, 0xe4, 0x5f, 0x88, 0x84, 0x6a, 0x63, 0x9b, 0xed, 0x35, 0x78, 0xac, 0x5d, 0xee, 0x11, 0x58,
	0x9f, 0x04, 0xd9, 0x5e, 0xd5, 0xae, 0x37, 0x71, 0xce, 0x77, 0x4e, 0x8e, 0xfd, 0x27, 0x81, 0x89,
	0xac, 0x66, 0x35, 0xff, 0x75, 0xd5, 0xad, 0x4b, 0xa9, 0x84, 0x11, 0xb4, 0x2f, 0xab, 0x69, 0xdc,
	0x8a, 0x56, 0x38, 0x39, 0xb3, 0x77, 0xde, 0x99, 0xbe, 0x6a, 0x45, 0x89, 0xa6, 0x6e, 0xca, 0x4e,
	0xcc, 0xec, 0x3a, 0x53, 0xfc, 0xd2, 0xb8, 0x8b, 0xac, 0xdc, 0xe2, 0x73, 0xf9, 0xdf, 0x3e, 0x84,
	0x17, 0x8a, 0xaf, 0x35, 0xaf, 0x4d, 0x27, 0xd6, 0xf4, 0x19, 0x8c, 0xaf, 0x55, 0x67, 0x70, 0xa5,
	0xd1, 0x24, 0x90, 0x05, 0x45, 0xc4, 0x46, 0x0e, 0x2c, 0xd1, 0xd0, 0xa7, 0x30, 0x52, 0xc8, 0x1b,
	0xe7, 0x85, 0xce, 0x1b, 0x5a, 0x6d, 0xad, 0x97, 0xf0, 0xd8, 0x59, 0xbb, 0x87, 0x23, 0x17, 0x88,
	0x2c, 0xfd, 0xb1, 0x2d, 0x78, 0x01, 0x4e, 0xa3, 0x5a, 0xad, 0x45, 0x83, 0x3a, 0x89, 0xb3, 0xa0,
	0x08, 0x58, 0xe8, 0xd9, 0x57, 0x8b, 0x6c, 0xc4, 0x75, 0x6c, 0x23, 0x27, 0x3e, 0xe2, 0x99, 0x8f,
	0x9c, 0xc2, 0xb1, 0x36, 0x42, 0x61, 0xb3, 0x92, 0x4a, 0xd4, 0xd8, 0xfc, 0x51, 0x98, 0xa4, 0x19,
	0x29, 0xc6, 0x6c, 0xe2, 0xf9, 0xb7, 0x2d, 0xa6, 0x73, 0x38, 0x39, 0x8c, 0xae, 0xb8, 0x6a, 0x75,
	0xf2, 0x3c, 0x23, 0x45, 0xc4, 0x9e, 0x1c, 0xe4, 0x3f, 0xa8, 0x56, 0xe7, 0x9f, 0xe0, 0x78, 0xef,
	0x8d, 0x9c, 0x71, 0x53, 0xff, 0xa4, 0x0b, 0x88, 0xcc, 0x8e, 0xe9, 0x84, 0x64, 0x41, 0x11, 0xce,
	0x27, 0xa5, 0xac, 0xca, 0xbd, 0x2c, 0x7b, 0x10, 0xca, 0x2f, 0x60, 0xb8, 0x34, 0x28, 0x19, 0xfe,
	0xa6, 0x29, 0x00, 0xe3, 0x97, 0xc6, 0x9e, 0xff, 0xbc, 0x49, 0x48, 0x46, 0x8a, 0x80, 0xed, 0x11,
	0x7a, 0x0a, 0xc3, 0x2f, 0xa8, 0x35, 0x6f, 0x31, 0xe9, 0x67, 0xc4, 0x55, 0xfb, 0x6f, 0x55, 0xde,
	0x63, 0xb6, 0xf5, 0xf3, 0x0c, 0x46, 0xbe, 0x55, 0x4b, 0x1a, 0xc3, 0xd1, 0x47, 0xa5, 0x84, 0x72,
	0x8d, 0x63, 0xe6, 0x45, 0xbe, 0x80, 0xa3, 0xf3, 0xe6, 0xed, 0xfc, 0x9d, 0xb5, 0xbf, 0x4b, 0x89,
	0xde, 0x1e, 0x30, 0x2f, 0x2c, 0xfd, 0x2c, 0xae, 0x51, 0xb9, 0x9d, 0x06, 0xcc, 0x8b, 0xf9, 0x7b,
	0x88, 0xed, 0x79, 0xdc, 0x34, 0x52, 0x28, 0xb3, 0x44, 0x75, 0xd5, 0xd5, 0x48, 0x5f, 0xc3, 0xc0,
	0x6e, 0x47, 0x43, 0x3b, 0xeb, 0xfd, 0x38, 0xd3, 0x68, 0x27, 0xb4, 0xcc, 0x7b, 0x05, 0x79, 0x43,
	0xce, 0xe2, 0x9b, 0xbb, 0xb4, 0x77, 0x7b, 0x97, 0xf6, 0x6e, 0x36, 0x29, 0xb9, 0xdd, 0xa4, 0xe4,
	0xdf, 0x26, 0x25, 0xd5, 0x23, 0xf7, 0x9b, 0x2d, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xfa,
	0xd3, 0xdf, 0xbb, 0x02, 0x00, 0x00,
}
